FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    torch \
    gymnasium \
    kafka-python \
    numpy

COPY rl_core/agent.py .
COPY rl_core/actor.py .

CMD ["python", "actor.py"]
